# Generated by Django 5.1.3 on 2024-11-27 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Invoice", "0002_customer_address_customer_city_customer_country_and_more"),
    ]

    operations = []
